---
- name: Trabajar con ficheros
  hosts: all

  tasks:
  - name: Copy en ubu y de
    ansible.builtin.file:
      path: "/tmp/Okl_funk"
      state: directory
    when: ansible_distribution | lower == "ubuntu" or ansible_distribution | lower == "debian"

  - name: Copy en redhat
    ansible.builtin.file:
      path: "/tmp/Para_q_funk"
      state: directory
    when: ansible_distribution | lower == "redhat"
...